pool:
  name: Azure Pipelines
  vmImage: 'windows-2022'
  demands:
    - npm
    - msbuild
    - MSBuild
    - Xamarin.Android
    - JDK

variables:
  branchName: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]

steps:
  - task: DeleteFiles@1
    displayName: 'Delete files from '
    inputs:
      Contents: |
        **/bin
        **/obj

  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet 5.8.0'
    inputs:
      versionSpec: 5.8.0

  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      restoreSolution: '*.sln'
      feedsToUse: config
      nugetConfigPath: nuget.config
      restoreDirectory: packages

  - task: XamarinAndroid@1
    displayName: 'Build aab (Android App Bundle)'
    inputs:
      projectFile: '*droid*/*Droid*.csproj'
      outputDirectory: '$(Build.BinariesDirectory)/bin/Release'
      configuration: Release
      msbuildVersionOption: latest
      msbuildArchitectureOption: x64
      msbuildArguments: '/p:SolutionDir="$(Build.SourcesDirectory)" -p:AndroidPackageFormat=aab -t:SignAndroidPackage -p:AndroidKeyStore=True -p:AndroidNdkDirectory="$(ANDROID_NDK_LATEST_HOME)"'

  - task: XamarinAndroid@1
    displayName: 'Build APK'
    inputs:
      projectFile: '*droid*/*Droid*.csproj'
      outputDirectory: '$(Build.BinariesDirectory)/bin/Release'
      configuration: Release
      msbuildVersionOption: latest
      msbuildArchitectureOption: x64
      msbuildArguments: '/p:SolutionDir="$(Build.SourcesDirectory)" -p:AndroidNdkDirectory="$(ANDROID_NDK_LATEST_HOME)"'

  - task: CopyFiles@1
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(Build.BinariesDirectory)/bin/Release'
      Contents: |
        *.apk
        *aab
      TargetFolder: '$(build.artifactstagingdirectory)'
      CleanTargetFolder: true
      flattenFolders: true

  - task: CopyFiles@2
    displayName: 'Copy Files Release notes'
    inputs:
      SourceFolder: 'release-notes'
      Contents: |
        $(ReleaseNotesName)
        test.md
        generic.md
      TargetFolder: '$(build.artifactstagingdirectory)'
      flattenFolders: true

  - task: NodeTool@0
    displayName: 'Use Node 10.x to run appcenter cmd'
    inputs:
      versionSpec: 10.x

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: BMM.Droid
